target = "https://www.rfc-editor.org/rfc/rfc6935#section-1"

# Introduction
#
#    This document constitutes an update of the IPv6 specification
#    [RFC2460] for cases where a tunnel protocol uses UDP with IPv6 to
#    tunnel packets.  With the rapid growth of the Internet, tunnel
#    protocols have become increasingly important to enable the deployment
#    of new protocols.  Tunnel protocols can be deployed rapidly, while
#    the time to upgrade and deploy a new protocol on a critical mass of
#    routers, middleboxes, and hosts on the global Internet is now
#    measured in decades.  At the same time, the increasing use of
#    firewalls and other security-related middleboxes means that truly new
#    tunnel protocols, with new protocol numbers, are also unlikely to be
#    deployable in a reasonable time frame.  The result is an increasing
#    interest in and use of UDP-based tunnel protocols.  In such
#    protocols, there is an encapsulated "inner" packet, and the "outer"
#    packet carrying the tunneled inner packet is a UDP packet, which can
#    pass through firewalls and other middleboxes that perform the
#    filtering that is a fact of life on the current Internet.
# 
#    Tunnel endpoints may be routers or middleboxes aggregating traffic
#    from a number of tunnel users.  Therefore, the computation of an
#    additional checksum on the outer UDP packet may be seen as an
#    unwarranted burden on nodes that implement a tunnel protocol,
#    especially if the inner packets are already protected by a checksum.
#    IPv4 has a checksum over the IP packet header, and the checksum on
#    the outer UDP packet may be set to zero.  However, IPv6 has no
#    checksum in the IP header, and RFC 2460 [RFC2460] explicitly states
#    that IPv6 receivers MUST discard UDP packets with a zero checksum.
#    So, while sending a UDP datagram with a zero checksum is permitted in
#    IPv4 packets, it is explicitly forbidden in IPv6 packets.  To improve
#    support for IPv6 UDP tunnels, this document updates RFC 2460 to allow
#    endpoints to use a zero UDP checksum under constrained situations
#    (primarily for IPv6 tunnel transports that carry checksum-protected
#    packets), following the applicability statements and constraints in
#    [RFC6936].
# 
#    When reading this document, the advice in "Unicast UDP Usage
#    Guidelines for Application Designers" [RFC5405] is applicable.  It
#    discusses both UDP tunnels (Section 3.1.3) and the usage of checksums
#    (Section 3.4).
# 
#    While the origin of this specification is the problem raised by the
#    draft titled "Automatic Multicast Tunnels", also known as "AMT"
#    [AMT], we expect it to have wide applicability.  Since the first
#    draft of this RFC was written, the need for an efficient UDP
#    tunneling mechanism has increased.  Other IETF Working Groups,
#    notably LISP [RFC6830] and Softwires [RFC5619], have expressed a need
# 
#    to update the UDP checksum processing in RFC 2460.  We therefore
#    expect this update to be applicable in the future to other tunnel
#    protocols specified by these and other IETF Working Groups.

[[spec]]
level = "MUST"
quote = '''
However, IPv6 has no
checksum in the IP header, and RFC 2460 [RFC2460] explicitly states
that IPv6 receivers MUST discard UDP packets with a zero checksum.
'''

