// SPDX-License-Identifier: Apache-2.0
// Copyright Open Network Fabric Authors

//! Type-carried structural proofs over [`Headers`].
//!
//! A [`Window<T>`] is a [`Headers`] that has been validated at construction
//! to conform to a specific shape `T`.  Downstream code that receives a
//! `Window<T>` can extract typed references to the matched layers via the
//! [`Look`] trait without re-validating at each access site.
//!
//! # Safety boundary
//!
//! Zero-cost extraction is achieved by informing the optimizer, via
//! `unreachable_unchecked`, that the `Window` type invariant rules out
//! the failure arms of layer-access match expressions.  The `unsafe`
//! required for this is fully contained:
//!
//! * [`Window::new`] is the only way to construct a `Window<T>`, and it
//!   validates the shape using [`ExtractUnchecked::try_extract`] for each
//!   layer in `T`.
//! * [`ExtractUnchecked`] is crate-private.  Its `extract_unchecked`
//!   method is `unsafe fn` and carries a presence-proof obligation which
//!   is discharged, once, by the `Window<T>` newtype invariant.
//! * External callers see only [`Window`] and [`Look`].  They cannot
//!   implement [`ExtractUnchecked`] or call it directly.
//!
//! This matches the "safe abstraction built from local unsafe
//! scaffolding" pattern in `development/code/unsafe-code.md`.

#![allow(unsafe_code)] // scaffolding for safe Window abstraction; see module docs

use core::marker::PhantomData;

use crate::eth::Eth;
use crate::ipv4::Ipv4;
use crate::ipv6::Ipv6;
use crate::tcp::Tcp;
use crate::udp::Udp;

use super::{Headers, Net, Transport};

/// A [`Headers`] whose structural shape has been validated at construction
/// to match the tuple type parameter `T`.
///
/// `T` is a reference-tuple marker (e.g. `(&Eth,)`,
/// `(&Eth, &Ipv4, &Tcp)`).  Its presence at the type level asserts that
/// the underlying [`Headers`] actually contains those layers in that
/// order.
///
/// Construct via [`Window::new`].  Extract typed references via
/// [`Look::look`].
#[repr(transparent)]
pub struct Window<T>(Headers, PhantomData<T>);

impl<T> Window<T> {
    /// Unwrap the `Window` back into the underlying [`Headers`].
    pub fn into_headers(self) -> Headers {
        self.0
    }
}

/// Extract typed references to the layers a [`Window<T>`] holds.
///
/// Implemented for each valid shape tuple `T`.  `Refs<'a>` is the tuple
/// of references returned by [`Self::look`].
pub trait Look<T> {
    /// The tuple of typed references produced by [`Self::look`].
    type Refs<'a>
    where
        Self: 'a;

    /// Extract typed references to the matched layers.
    ///
    /// Compiles to pure field-offset computations; the `Window` type
    /// invariant guarantees presence so no runtime check is needed.
    fn look<'a>(&'a self) -> Self::Refs<'a>
    where
        Self: 'a;
}

/// Crate-private: maps a layer type to its location in [`Headers`].
///
/// Consumers never see this trait.  It exists as internal scaffolding
/// for the [`Look`] impls generated by [`define_window!`].
pub(crate) trait ExtractUnchecked: Sized {
    /// Safely attempt to extract a reference to `Self` from `h`.  Used
    /// by [`Window::new`] to validate the shape at construction.
    fn try_extract(h: &Headers) -> Option<&Self>;

    /// Extract a reference to `Self` from `h`, assuming presence.
    ///
    /// # Safety
    ///
    /// The caller must hold a proof that `Self` is structurally present
    /// in `h`.  The `Window<T>` newtype invariant (established by
    /// [`Window::new`]) is such a proof for any `Self` whose reference
    /// appears in `T`.  Calling this without such a proof is undefined
    /// behavior.
    #[inline(always)]
    unsafe fn extract_unchecked(h: &Headers) -> &Self {
        match Self::try_extract(h) {
            Some(x) => x,
            None => unsafe { core::hint::unreachable_unchecked() },
        }
    }
}

impl ExtractUnchecked for Eth {
    #[inline(always)]
    fn try_extract(h: &Headers) -> Option<&Eth> {
        h.eth()
    }
}

impl ExtractUnchecked for Ipv4 {
    #[inline(always)]
    fn try_extract(h: &Headers) -> Option<&Ipv4> {
        match h.net() {
            Some(Net::Ipv4(ip)) => Some(ip),
            _ => None,
        }
    }
}

impl ExtractUnchecked for Ipv6 {
    #[inline(always)]
    fn try_extract(h: &Headers) -> Option<&Ipv6> {
        match h.net() {
            Some(Net::Ipv6(ip)) => Some(ip),
            _ => None,
        }
    }
}

impl ExtractUnchecked for Tcp {
    #[inline(always)]
    fn try_extract(h: &Headers) -> Option<&Tcp> {
        match h.transport() {
            Some(Transport::Tcp(t)) => Some(t),
            _ => None,
        }
    }
}

impl ExtractUnchecked for Udp {
    #[inline(always)]
    fn try_extract(h: &Headers) -> Option<&Udp> {
        match h.transport() {
            Some(Transport::Udp(u)) => Some(u),
            _ => None,
        }
    }
}

/// Expand a shape (list of layer types) into:
/// - an `impl<'x> Window<(&'x T1, &'x T2, ...)>` with a `new` that
///   validates the shape,
/// - an `impl<'x> Look<(&'x T1, ...)> for Window<...>` whose `look`
///   is zero-cost under the `Window` invariant.
///
/// Crate-private.  External crates compose pre-defined shapes rather
/// than declare new ones.  Adding a shape is a one-line change here.
macro_rules! define_window {
    ($($ty:ty),+ $(,)?) => {
        impl<'x> Window<($(&'x $ty,)+)>
        where
            Self: 'x,
        {
            /// Validate the shape and construct a `Window` on success,
            /// returning the original [`Headers`] on failure.
            pub fn new(headers: Headers) -> Result<Self, Headers> {
                let ok = true
                    $( && <$ty as ExtractUnchecked>::try_extract(&headers).is_some() )+;
                if ok {
                    Ok(Window(headers, PhantomData))
                } else {
                    Err(headers)
                }
            }
        }

        impl<'x> Look<($(&'x $ty,)+)> for Window<($(&'x $ty,)+)>
        where
            Self: 'x,
        {
            type Refs<'a>
                = ($(&'a $ty,)+)
            where
                Self: 'a;

            #[inline(always)]
            fn look<'a>(&'a self) -> Self::Refs<'a>
            where
                Self: 'a,
            {
                unsafe {
                    (
                        $( <$ty as ExtractUnchecked>::extract_unchecked(&self.0), )+
                    )
                }
            }
        }
    };
}

define_window!(Eth);
define_window!(Eth, Ipv4);
define_window!(Eth, Ipv6);
define_window!(Eth, Ipv4, Tcp);
define_window!(Eth, Ipv4, Udp);
define_window!(Eth, Ipv6, Tcp);
define_window!(Eth, Ipv6, Udp);
