target = "https://www.rfc-editor.org/rfc/rfc5382#section-5"


[[spec]]
level = "MAY"
quote = '''
REQ-5:  If a NAT cannot determine whether the endpoints of a TCP
connection are active, it MAY abandon the session if it has been
idle for some time.
'''

[[spec]]
level = "MUST"
quote = '''
In such cases, the value of the "established
connection idle-timeout" MUST NOT be less than 2 hours 4 minutes.
'''

[[spec]]
level = "MUST"
quote = '''
The value of the "transitory connection idle-timeout" MUST NOT be
less than 4 minutes.
'''

[[spec]]
level = "MAY"
quote = '''
a) The value of the NAT idle-timeouts MAY be configurable.
'''

[[spec]]
level = "MAY"
quote = '''
A NAT MAY hold state for a connection in
TIME_WAIT state to accommodate retransmissions of the last ACK.
'''

[[spec]]
level = "MAY"
quote = '''
When a NAT abandons a live connection, for
example due to a timeout expiring, the NAT MAY either send TCP RST
packets to the endpoints or MAY silently abandon the connection.
'''

