version: 2

updates:
  - package-ecosystem: "cargo"
    target-branch: "main"
    directories:
      - /
    schedule:
      interval: "weekly"
    versioning-strategy: "lockfile-only"
    groups:
      dev-dependencies:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
