version: 2

updates:
  - package-ecosystem: "github-actions"
    target-branch: "main"
    commit-message:
      prefix: "bump(github-actions):"
    directories:
      - "/"
    schedule:
      interval: "weekly"
    labels:
      - "automated"
      - "dependencies"
  - package-ecosystem: "cargo"
    target-branch: "main"
    commit-message:
      prefix: "bump(cargo):"
    directories:
      - "/"
    schedule:
      interval: "weekly"
    labels:
      - "automated"
      - "dependencies"
    versioning-strategy: "increase-if-necessary"
    groups:
      dependencies:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
