words = [
    "ack",
    "dataplane",
    "dpdk",
    "eal",
    "frr",
    "hwloc",
    "hwlocality",
    "ide's",
    "iova",
    "ipc",
    "keepalives",
    "lcore",
    "lcores",
    "libgcc",
    "loglevel",
    "mcs",
    "memfd",
    "mlx",
    "netlink",
    "nextest",
    "nic",
    "nics",
    "numa",
    "pci",
    "pmd",
    "qsbr",
    "rcu",
    "rprivate",
    "setcap",
    "smt",
    "tokio",
    "uncore",
    "vfio",
    "vhost",
    "virtio",
    "vlab",
]
