words = [
    "ack",
    "cpus",
    "dataplane",
    "dpdk",
    "eal",
    "ebdf",
    "efa",
    "errno",
    "frr",
    "hwloc",
    "hwlocality",
    "ide's",
    "iova",
    "ipc",
    "keepalives",
    "lcore",
    "lcores",
    "libgcc",
    "loglevel",
    "lpm",
    "lro",
    "lto",
    "mbuf",
    "mcs",
    "memfd",
    "mgmt",
    "mlx",
    "mpls",
    "mtu",
    "netlink",
    "newtype",
    "nextest",
    "nic",
    "nics",
    "numa",
    "numanode",
    "osdevice",
    "pci",
    "pktmbuf",
    "pmd",
    "qsbr",
    "raii",
    "rcu",
    "rekon",
    "rkyv",
    "rprivate",
    "serde",
    "setcap",
    "smt",
    "subdevice",
    "subvendor",
    "tailroom",
    "tokio",
    "topo",
    "tracectl",
    "uncore",
    "vfio",
    "vhost",
    "virtio",
    "vlab",
    "vni",
    "vpc",
    "vpcmap",
    "ツ",
]
