words = [
    "ack",
    "dpdk",
    "eal",
    "keepalives",
    "lcore",
    "lcores",
    "mcs",
    "memfd",
    "netlink",
    "nic",
    "nics",
    "numa",
    "pmd",
    "qsbr",
    "rcu",
    "smt",
    "tokio",
    "uncore",
    "vfio",
    "virtio",
    "vlab",
]
