words = [
    "ack",
    "afl",
    "bdf",
    "cardinalities",
    "cgnat",
    "clippy",
    "cov",
    "cpus",
    "dataplane",
    "dddd",
    "dma",
    "doctests",
    "dpdk",
    "dpdk's",
    "dplane",
    "drawio",
    "eal",
    "ebdf",
    "efa",
    "eprintln",
    "errno",
    "ffff",
    "fredi",
    "frr",
    "hwloc",
    "hwlocality",
    "hwlocality's",
    "ide's",
    "infini",
    "infiniband",
    "infty",
    "iova",
    "ipc",
    "ipv",
    "keepalives",
    "lcore",
    "lcores",
    "libfuzzer",
    "libgcc",
    "llm",
    "loglevel",
    "lpm",
    "lro",
    "lto",
    "markdownlint",
    "mathrm",
    "mbuf",
    "mcs",
    "memfd",
    "mgmt",
    "mlx",
    "mpls",
    "mtu",
    "mytarget",
    "netlink",
    "newtype",
    "nextest",
    "nic",
    "nics",
    "numa",
    "numanode",
    "oom",
    "osdevice",
    "pci",
    "pktmbuf",
    "pmd",
    "programmatically",
    "proptest",
    "prost",
    "psh",
    "qsbr",
    "raii",
    "rcu",
    "refake",
    "rekon",
    "rkyv",
    "rprivate",
    "rustdoc",
    "rustflags",
    "rustup",
    "serde",
    "setcap",
    "smt",
    "subdevice",
    "subvendor",
    "tailroom",
    "tctl",
    "tdebug",
    "testn",
    "thiserror",
    "tinfo",
    "tlb",
    "tokio",
    "topo",
    "tracectl",
    "ttrace",
    "twarn",
    "typestate",
    "uncore",
    "unrepresentable",
    "urg",
    "vfio",
    "vhost",
    "virtio",
    "vlab",
    "vni",
    "vpc",
    "vpcmap",
    "vscode",
    "vxlan",
    "ツ",
]
