comment: false
coverage:
  status:
    project:
      default:
        # Our usage is intended for discussion and analysis in PRs
        # we have no explicit coverage target at the moment.
        informational: true
    patch:
      default:
        informational: true
