#!/bin/bash

set -uxo pipefail

just _test_type=FUZZ fuzz test::new_generates_unique --jobs=30 -T 500sec
just _test_type=FUZZ fuzz test::test_v5 --jobs=30 -T 500sec
just _test_type=FUZZ fuzz test::test_static --jobs=30 -T 500sec
just _test_type=FUZZ fuzz stateless::iplist::tests::test_bolero_iplist_subset --jobs=30 -T 500sec
just _test_type=FUZZ fuzz eth::mac::test::test_mac_from_valid_string --jobs=30 -T 500sec
just _test_type=FUZZ fuzz eth::mac::test::test_mac_from_invalid_string --jobs=30 -T 500sec
just _test_type=FUZZ fuzz eth::test::parse_arbitrary_bytes --jobs=30 -T 500sec
just _test_type=FUZZ fuzz eth::test::parse_back --jobs=30 -T 500sec
just _test_type=FUZZ fuzz eth::test::parse_prop_test_buffer_too_short --jobs=30 -T 500sec
just _test_type=FUZZ fuzz eth::test::parse_prop_test_excess_buffer --jobs=30 -T 500sec
just _test_type=FUZZ fuzz headers::test::parse_back_common --jobs=30 -T 500sec
just _test_type=FUZZ fuzz headers::test::parse_back --jobs=30 -T 500sec
just _test_type=FUZZ fuzz icmp4::test::parse_back --jobs=30 -T 500sec
just _test_type=FUZZ fuzz icmp6::test::parse_arbitrary_bytes --jobs=30 -T 500sec
just _test_type=FUZZ fuzz icmp6::test::parse_back --jobs=30 -T 500sec
just _test_type=FUZZ fuzz interface::mtu::test::mtu_is_constrained --jobs=30 -T 500sec
just _test_type=FUZZ fuzz interface::test::interface_name_validates --jobs=30 -T 500sec
just _test_type=FUZZ fuzz interface::test::interface_name_with_illegal_char_rejects --jobs=30 -T 500sec
just _test_type=FUZZ fuzz interface::test::interface_name_with_null_char_rejects --jobs=30 -T 500sec
just _test_type=FUZZ fuzz interface::test::too_long_interface_name_rejected --jobs=30 -T 500sec
just _test_type=FUZZ fuzz ip::tests::generated_unicast_ip_address_is_unicast --jobs=30 -T 500sec
just _test_type=FUZZ fuzz ip::tests::try_from_obeys_contract --jobs=30 -T 500sec
just _test_type=FUZZ fuzz ip::tests::unicast_ipv4_is_unicast_ip --jobs=30 -T 500sec
just _test_type=FUZZ fuzz ip::tests::unicast_ipv6_is_unicast_ip --jobs=30 -T 500sec
just _test_type=FUZZ fuzz ipv4::addr::test::generated_unicast_ipv4_address_is_unicast --jobs=30 -T 500sec
just _test_type=FUZZ fuzz ipv4::prefix::tests::address_containment --jobs=30 -T 500sec
just _test_type=FUZZ fuzz ipv4::prefix::tests::basic_fuzz --jobs=30 -T 500sec
just _test_type=FUZZ fuzz ipv4::prefix::tests::contained_logic_fuzzing --jobs=30 -T 500sec
just _test_type=FUZZ fuzz ipv4::prefix::tests::containment_logic_soundness --jobs=30 -T 500sec
just _test_type=FUZZ fuzz ipv4::prefix::tests::overlap_detection --jobs=30 -T 500sec
just _test_type=FUZZ fuzz ipv4::prefix::tests::prefix_generator_soundness --jobs=30 -T 500sec
just _test_type=FUZZ fuzz ipv4::prefix::tests::prefix_logic_soundness --jobs=30 -T 500sec
just _test_type=FUZZ fuzz ipv4::test::parse_arbitrary_bytes --jobs=30 -T 500sec
just _test_type=FUZZ fuzz ipv4::test::parse_back --jobs=30 -T 500sec
just _test_type=FUZZ fuzz ipv6::addr::test::generated_unicast_ipv4_address_is_unicast --jobs=30 -T 500sec
just _test_type=FUZZ fuzz ipv6::prefix::tests::address_containment --jobs=30 -T 500sec
just _test_type=FUZZ fuzz ipv6::prefix::tests::basic_fuzz --jobs=30 -T 500sec
just _test_type=FUZZ fuzz ipv6::prefix::tests::containment_logic_soundness --jobs=30 -T 500sec
just _test_type=FUZZ fuzz ipv6::prefix::tests::contained_logic_fuzzing --jobs=30 -T 500sec
just _test_type=FUZZ fuzz ipv6::prefix::tests::prefix_generator_soundness --jobs=30 -T 500sec
just _test_type=FUZZ fuzz ipv6::prefix::tests::overlap_detection --jobs=30 -T 500sec
just _test_type=FUZZ fuzz ipv6::prefix::tests::prefix_logic_soundness --jobs=30 -T 500sec
just _test_type=FUZZ fuzz ipv6::test::parse_arbitrary_bytes --jobs=30 -T 500sec
just _test_type=FUZZ fuzz ipv6::test::parse_arbitrary_bytes_above_minimum --jobs=30 -T 500sec
just _test_type=FUZZ fuzz ipv6::test::parse_arbitrary_bytes_too_short --jobs=30 -T 500sec
just _test_type=FUZZ fuzz ipv6::test::parse_back --jobs=30 -T 500sec
just _test_type=FUZZ fuzz pci::tests::parse_arbitrary_string --jobs=30 -T 500sec
just _test_type=FUZZ fuzz pci::tests::parse_valid --jobs=30 -T 500sec
just _test_type=FUZZ fuzz vlan::test::deparse_to_insufficient_buffer_is_graceful --jobs=30 -T 500sec
just _test_type=FUZZ fuzz tcp::test::parse_back --jobs=30 -T 500sec
just _test_type=FUZZ fuzz vlan::test::parse_back --jobs=30 -T 500sec
just _test_type=FUZZ fuzz vlan::test::pcp_bounds_respected --jobs=30 -T 500sec
just _test_type=FUZZ fuzz udp::test::parse_arbitrary_bytes --jobs=30 -T 500sec
just _test_type=FUZZ fuzz udp::test::arbitrary_mutation --jobs=30 -T 500sec
just _test_type=FUZZ fuzz udp::test::longer_buffer_parses_ok --jobs=30 -T 500sec
just _test_type=FUZZ fuzz vxlan::test::parse_back --jobs=30 -T 500sec
just _test_type=FUZZ fuzz vxlan::test::parse_noise --jobs=30 -T 500sec
just _test_type=FUZZ fuzz vlan::test::arbitrary_mutation --jobs=30 -T 500sec
just _test_type=FUZZ fuzz vxlan::test::parse_of_insufficient_buffer_fails_gracefully --jobs=30 -T 500sec
just _test_type=FUZZ fuzz vlan::test::parse_noise --jobs=30 -T 500sec
just _test_type=FUZZ fuzz vlan::test::parse_noise_too_short --jobs=30 -T 500sec
just _test_type=FUZZ fuzz vxlan::test::write_to_insufficient_buffer_fails_gracefully --jobs=30 -T 500sec
just _test_type=FUZZ fuzz vxlan::vni::test::arbitrary_value_complies_with_contract --jobs=30 -T 500sec
just _test_type=FUZZ fuzz vxlan::vni::test::try_from_produces_only_values_which_comply_with_contract_or_which_return_correct_errors --jobs=30 -T 500sec
just _test_type=FUZZ fuzz tcp::test::parse_noise --jobs=30 -T 500sec
just _test_type=FUZZ fuzz udp::test::too_short_buffer_parse_fails_gracefully --jobs=30 -T 500sec
just _test_type=FUZZ fuzz udp::test::parse_back --jobs=30 -T 500sec
just _test_type=FUZZ fuzz vxlan::test::mutation_of_header_preserves_contract --jobs=30 -T 500sec
just _test_type=FUZZ fuzz vxlan::test::creation_identity_check --jobs=30 -T 500sec
just _test_type=FUZZ fuzz prefix::tests::test_bolero_prefixsize_compare --jobs=30 -T 500sec
