target = "https://www.rfc-editor.org/rfc/rfc5508#section-9"

# Summary of Requirements
#
#    Below is a summary of all the requirements.
# 
#    REQ-1: Unless explicitly overridden by local policy, a NAT device
#           MUST permit ICMP Queries and their associated responses, when
#           the Query is initiated from a private host to the external
#           hosts.
# 
#           a) NAT mapping of ICMP Query Identifiers SHOULD be external
#              host independent.
# 
#    REQ-2: An ICMP Query session timer MUST NOT expire in less than 60
#           seconds.
# 
#           a) It is RECOMMENDED that the ICMP Query session timer be made
#              configurable.
# 
#    REQ-3: When an ICMP Error packet is received, if the ICMP checksum
#           fails to validate, the NAT SHOULD silently drop the ICMP Error
#           packet.  If the ICMP checksum is valid, do the following:
# 
#           a) If the IP checksum of the embedded packet fails to
#              validate, the NAT SHOULD silently drop the Error packet;
#              and
# 
#           b) If the embedded packet includes IP options, the NAT device
#              MUST traverse past the IP options to locate the start of
#              the transport header for the embedded packet; and
# 
#           c) The NAT device SHOULD NOT validate the transport checksum
#              of the embedded packet within an ICMP Error message, even
#              when it is possible to do so; and
# 
#           d) If the ICMP Error payload contains ICMP extensions
#              [ICMP-EXT], the NAT device MUST exclude the optional zero-
#              padding and the ICMP extensions when evaluating transport
#              checksum for the embedded packet.
# 
#    REQ-4: If a NAT device receives an ICMP Error packet from an external
#           realm, and the NAT device does not have an active mapping for
#           the embedded payload, the NAT SHOULD silently drop the ICMP
#           Error packet.  If the NAT has active mapping for the embedded
#           payload, then the NAT MUST do the following prior to
#           forwarding the packet, unless explicitly overridden by local
#           policy:
# 
#           a) Revert the IP and transport headers of the embedded IP
#              packet to their original form, using the matching mapping;
#              and
# 
#           b) Leave the ICMP Error type and code unchanged; and
# 
#           c) Modify the destination IP address of the outer IP header to
#              be same as the source IP address of the embedded packet
#              after translation.
# 
#    REQ-5: If a NAT device receives an ICMP Error packet from the private
#           realm, and the NAT does not have an active mapping for the
#           embedded payload, the NAT SHOULD silently drop the ICMP Error
#           packet.  If the NAT has active mapping for the embedded
#           payload, then the NAT MUST do the following prior to
#           forwarding the packet, unless explicitly overridden by local
#           policy.
# 
#           a) Revert the IP and transport headers of the embedded IP
#              packet to their original form, using the matching mapping;
#              and
# 
#           b) Leave the ICMP Error type and code unchanged; and
# 
#           c) If the NAT enforces Basic NAT function [NAT-TRAD], and the
#              NAT has active mapping for the IP address that sent the
#              ICMP Error, translate the source IP address of the ICMP
#              Error packet with the public IP address in the mapping.  In
#              all other cases, translate the source IP address of the
#              ICMP Error packet with its own public IP address.
# 
#    REQ-6: While processing an ICMP Error packet pertaining to an ICMP
#           Query or Query response message, a NAT device MUST NOT refresh
#           or delete the NAT Session that pertains to the embedded
#           payload within the ICMP Error packet.
# 
#    REQ-7: NAT devices enforcing Basic NAT ([NAT-TRAD]) MUST support the
#           traversal of hairpinned ICMP Query sessions.  All NAT devices
#           (i.e., Basic NAT as well as NAPT devices) MUST support the
#           traversal of hairpinned ICMP Error messages.
# 
#           a) When forwarding a hairpinned ICMP Error message, the NAT
#              device MUST translate the destination IP address of the
#              outer IP header to be same as the source IP address of the
#              embedded IP packet after the translation.
# 
#    REQ-8: When a NAT device is unable to establish a NAT Session for a
#           new transport-layer (TCP, UDP, ICMP, etc.) flow due to
#           resource constraints or administrative restrictions, the NAT
#           device SHOULD send an ICMP destination unreachable message,
#           with a code of 13 (Communication administratively prohibited)
#           to the sender, and drop the original packet.
# 
#    REQ-9: A NAT device MAY implement a policy control that prevents ICMP
#           messages being generated toward certain interface(s).
#           Implementation of such a policy control overrides the MUSTs
#           and SHOULDs in REQ-10.
# 
#    REQ-10: Unless overridden by REQ-9's policy, a NAT device needs to
#            support ICMP messages as below, some conforming to Section
#            4.3 of [RFC1812] and some superseding the requirements of
#            Section 4.3 of [RFC1812]:
# 
#           a. MUST support:
# 
#              1. Destination Unreachable Message, as described in Section
#                 7.1 of this document.
# 
#              2. Time Exceeded Message, as described in Section 7.2 of
#                 this document.
# 
#              3. Echo Request/Reply Messages, as described in REQ-1.
# 
#           b. MAY support:
# 
#              1. Redirect Message, as described in Section 4.3.3.2 of
#                 [RFC1812].
# 
#              2. Timestamp and Timestamp Reply Messages, as described in
#                 Section 4.3.3.8 of [RFC1812].
# 
#              3. Source Route Options, as described in Section 7.3 of
#                 this document.
# 
#              4. Address Mask Request/Reply Message, as described in
#                 Section 7.4 of this document.
# 
#              5. Parameter Problem Message, as described in Section 7.5
#                 of this document.
# 
#              6. Router Advertisement and Solicitations, as described in
#                 Section 7.6 of this document.
# 
#           c. SHOULD NOT support:
# 
#              1. Source Quench Message, as described in Section 4.3.3.3
#                 of [RFC1812].
# 
#              2. Information Request/reply, as described in Section
#                 4.3.3.7 of [RFC1812].
# 
#           In addition, a NAT device is RECOMMENDED to conform to the
#           following implementation considerations:
# 
#           d. DS Field Usage, as described in Section 7.7 of this
#              document.
# 
#           e. When Not to Send ICMP Errors, as described in Section
#              4.3.2.7 of [RFC1812].
# 
#           f. Rate Limiting, as described in Section 4.3.2.8 of
#              [RFC1812].
# 
#    REQ-11: A NAT MAY drop or appropriately handle Non-QueryError ICMP
#            messages.  The semantics of Non-QueryError ICMP messages is
#            defined in Section 2.

[[spec]]
level = "MUST"
quote = '''
REQ-1: Unless explicitly overridden by local policy, a NAT device
MUST permit ICMP Queries and their associated responses, when
the Query is initiated from a private host to the external
hosts.
'''

[[spec]]
level = "SHOULD"
quote = '''
a) NAT mapping of ICMP Query Identifiers SHOULD be external
host independent.
'''

[[spec]]
level = "MUST"
quote = '''
REQ-2: An ICMP Query session timer MUST NOT expire in less than 60
seconds.
'''

[[spec]]
level = "SHOULD"
quote = '''
a) It is RECOMMENDED that the ICMP Query session timer be made
configurable.
'''

[[spec]]
level = "SHOULD"
quote = '''
REQ-3: When an ICMP Error packet is received, if the ICMP checksum
fails to validate, the NAT SHOULD silently drop the ICMP Error
packet.
'''

[[spec]]
level = "SHOULD"
quote = '''
a) If the IP checksum of the embedded packet fails to
validate, the NAT SHOULD silently drop the Error packet;
and
'''

[[spec]]
level = "MUST"
quote = '''
b) If the embedded packet includes IP options, the NAT device
MUST traverse past the IP options to locate the start of
the transport header for the embedded packet; and
'''

[[spec]]
level = "SHOULD"
quote = '''
c) The NAT device SHOULD NOT validate the transport checksum
of the embedded packet within an ICMP Error message, even
when it is possible to do so; and
'''

[[spec]]
level = "MUST"
quote = '''
d) If the ICMP Error payload contains ICMP extensions
[ICMP-EXT], the NAT device MUST exclude the optional zero-
padding and the ICMP extensions when evaluating transport
checksum for the embedded packet.
'''

[[spec]]
level = "SHOULD"
quote = '''
REQ-4: If a NAT device receives an ICMP Error packet from an external
realm, and the NAT device does not have an active mapping for
the embedded payload, the NAT SHOULD silently drop the ICMP
Error packet.
'''

[[spec]]
level = "MUST"
quote = '''
If the NAT has active mapping for the embedded
payload, then the NAT MUST do the following prior to
forwarding the packet, unless explicitly overridden by local
policy:
'''

[[spec]]
level = "SHOULD"
quote = '''
REQ-5: If a NAT device receives an ICMP Error packet from the private
realm, and the NAT does not have an active mapping for the
embedded payload, the NAT SHOULD silently drop the ICMP Error
packet.
'''

[[spec]]
level = "MUST"
quote = '''
If the NAT has active mapping for the embedded
payload, then the NAT MUST do the following prior to
forwarding the packet, unless explicitly overridden by local
policy.
'''

[[spec]]
level = "MUST"
quote = '''
REQ-6: While processing an ICMP Error packet pertaining to an ICMP
Query or Query response message, a NAT device MUST NOT refresh
or delete the NAT Session that pertains to the embedded
payload within the ICMP Error packet.
'''

[[spec]]
level = "MUST"
quote = '''
REQ-7: NAT devices enforcing Basic NAT ([NAT-TRAD]) MUST support the
traversal of hairpinned ICMP Query sessions.
'''

[[spec]]
level = "MUST"
quote = '''
All NAT devices
(i.e., Basic NAT as well as NAPT devices) MUST support the
traversal of hairpinned ICMP Error messages.
'''

[[spec]]
level = "MUST"
quote = '''
a) When forwarding a hairpinned ICMP Error message, the NAT
device MUST translate the destination IP address of the
outer IP header to be same as the source IP address of the
embedded IP packet after the translation.
'''

[[spec]]
level = "SHOULD"
quote = '''
REQ-8: When a NAT device is unable to establish a NAT Session for a
new transport-layer (TCP, UDP, ICMP, etc.) flow due to
resource constraints or administrative restrictions, the NAT
device SHOULD send an ICMP destination unreachable message,
with a code of 13 (Communication administratively prohibited)
to the sender, and drop the original packet.
'''

[[spec]]
level = "MAY"
quote = '''
REQ-9: A NAT device MAY implement a policy control that prevents ICMP
messages being generated toward certain interface(s).
'''

[[spec]]
level = "MUST"
quote = '''
MUST support:
'''

[[spec]]
level = "MAY"
quote = '''
MAY support:
'''

[[spec]]
level = "SHOULD"
quote = '''
SHOULD NOT support:
'''

[[spec]]
level = "SHOULD"
quote = '''
In addition, a NAT device is RECOMMENDED to conform to the
following implementation considerations:
'''

[[spec]]
level = "MAY"
quote = '''
REQ-11: A NAT MAY drop or appropriately handle Non-QueryError ICMP
messages.
'''

