target = "https://www.rfc-editor.org/rfc/rfc5508#section-7.4"


[[spec]]
level = "MUST"
quote = '''
Section 4.3.3.9 of [RFC1812] says an IP router MUST implement support
for receiving ICMP Address Mask Request messages and responding with
ICMP Address Mask Reply messages.
'''

[[spec]]
level = "MAY"
quote = '''
A NAT device MAY support address mask request/reply messages.
'''

