target = "https://www.rfc-editor.org/rfc/rfc4884#section-3"

# Summary of Changes to ICMP
#
#    The following is a summary of changes to ICMP that are introduced by
#    this memo:
# 
#       An ICMP Extension Structure MAY be appended to ICMPv4 Destination
#       Unreachable, Time Exceeded, and Parameter Problem messages.
# 
#       An ICMP Extension Structure MAY be appended to ICMPv6 Destination
#       Unreachable, and Time Exceeded messages.
# 
#       The above mentioned messages include an "original datagram" field,
#       and the message formats are updated to specify a length attribute
#       for the "original datagram" field.
# 
#       When the ICMP Extension Structure is appended to an ICMP message
#       and that ICMP message contains an "original datagram" field, the
#       "original datagram" field MUST contain at least 128 octets.
# 
#       When the ICMP Extension Structure is appended to an ICMPv4 message
#       and that ICMPv4 message contains an "original datagram" field, the
#       "original datagram" field MUST be zero padded to the nearest
#       32-bit boundary.
# 
#       When the ICMP Extension Structure is appended to an ICMPv6 message
#       and that ICMPv6 message contains an "original datagram" field, the
#       "original datagram" field MUST be zero padded to the nearest
#       64-bit boundary.
# 
#       ICMP messages defined in the future SHOULD indicate whether or not
#       they support the extension mechanism defined in this
#       specification.  It is recommended that all new messages support
#       extensions.

[[spec]]
level = "MAY"
quote = '''
An ICMP Extension Structure MAY be appended to ICMPv4 Destination
Unreachable, Time Exceeded, and Parameter Problem messages.
'''

[[spec]]
level = "MAY"
quote = '''
An ICMP Extension Structure MAY be appended to ICMPv6 Destination
Unreachable, and Time Exceeded messages.
'''

[[spec]]
level = "MUST"
quote = '''
When the ICMP Extension Structure is appended to an ICMP message
and that ICMP message contains an "original datagram" field, the
"original datagram" field MUST contain at least 128 octets.
'''

[[spec]]
level = "MUST"
quote = '''
When the ICMP Extension Structure is appended to an ICMPv4 message
and that ICMPv4 message contains an "original datagram" field, the
"original datagram" field MUST be zero padded to the nearest
32-bit boundary.
'''

[[spec]]
level = "MUST"
quote = '''
When the ICMP Extension Structure is appended to an ICMPv6 message
and that ICMPv6 message contains an "original datagram" field, the
"original datagram" field MUST be zero padded to the nearest
64-bit boundary.
'''

[[spec]]
level = "SHOULD"
quote = '''
ICMP messages defined in the future SHOULD indicate whether or not
they support the extension mechanism defined in this
specification.
'''

