// SPDX-License-Identifier: Apache-2.0
// Copyright Open Network Fabric Authors

//! Autogenerated CRD sample/templates

use k8s_intf::samplegen::generate_samples;

const SAMPLES_OUT_DIR: &str = "generated-samples";
const SAMPLE_FILE_NAME: &str = "sample";

fn main() {
    if let Err(e) = generate_samples(SAMPLES_OUT_DIR, SAMPLE_FILE_NAME) {
        eprintln!("Failed to generate CRD JSON/YAML samples: {e}");
        std::process::exit(1);
    }
    println!("Successfully generated CRD JSON + YAML samples in folder '{SAMPLES_OUT_DIR}'");
}
