target = "https://www.rfc-editor.org/rfc/rfc4787#section-12"


[[spec]]
level = "MUST"
quote = '''
REQ-1:  A NAT MUST have an "Endpoint-Independent Mapping" behavior.
'''

[[spec]]
level = "SHOULD"
quote = '''
REQ-2:  It is RECOMMENDED that a NAT have an "IP address pooling"
behavior of "Paired".
'''

[[spec]]
level = "MUST"
quote = '''
REQ-3:  A NAT MUST NOT have a "Port assignment" behavior of "Port
overloading".
'''

[[spec]]
level = "SHOULD"
quote = '''
a) If the host's source port was in the range 0-1023, it is
RECOMMENDED the NAT's source port be in the same range.
'''

[[spec]]
level = "SHOULD"
quote = '''
If the
host's source port was in the range 1024-65535, it is
RECOMMENDED that the NAT's source port be in that range.
'''

[[spec]]
level = "SHOULD"
quote = '''
REQ-4:  It is RECOMMENDED that a NAT have a "Port parity
preservation" behavior of "Yes".
'''

[[spec]]
level = "MUST"
quote = '''
REQ-5:  A NAT UDP mapping timer MUST NOT expire in less than two
minutes, unless REQ-5a applies.
'''

[[spec]]
level = "MAY"
quote = '''
a) For specific destination ports in the well-known port range
(ports 0-1023), a NAT MAY have shorter UDP mapping timers that
are specific to the IANA-registered application running over
that specific destination port.
'''

[[spec]]
level = "MAY"
quote = '''
b) The value of the NAT UDP mapping timer MAY be configurable.
'''

[[spec]]
level = "SHOULD"
quote = '''
c) A default value of five minutes or more for the NAT UDP mapping
timer is RECOMMENDED.
'''

[[spec]]
level = "MUST"
quote = '''
REQ-6:  The NAT mapping Refresh Direction MUST have a "NAT Outbound
refresh behavior" of "True".
'''

[[spec]]
level = "MAY"
quote = '''
a) The NAT mapping Refresh Direction MAY have a "NAT Inbound
refresh behavior" of "True".
'''

[[spec]]
level = "MUST"
quote = '''
REQ-7  A NAT device whose external IP interface can be configured
dynamically MUST either (1) Automatically ensure that its internal
network uses IP addresses that do not conflict with its external
network, or (2) Be able to translate and forward traffic between
all internal nodes and all external nodes whose IP addresses
numerically conflict with the internal network.
'''

[[spec]]
level = "SHOULD"
quote = '''
REQ-8:  If application transparency is most important, it is
RECOMMENDED that a NAT have "Endpoint-Independent Filtering"
behavior.
'''

[[spec]]
level = "SHOULD"
quote = '''
If a more stringent filtering behavior is most
important, it is RECOMMENDED that a NAT have "Address-Dependent
Filtering" behavior.
'''

[[spec]]
level = "MAY"
quote = '''
a) The filtering behavior MAY be an option configurable by the
administrator of the NAT.
'''

[[spec]]
level = "MUST"
quote = '''
REQ-9:  A NAT MUST support "Hairpinning".
'''

[[spec]]
level = "MUST"
quote = '''
a) A NAT Hairpinning behavior MUST be "External source IP address
and port".
'''

[[spec]]
level = "SHOULD"
quote = '''
REQ-10:  To eliminate interference with UNSAF NAT traversal
mechanisms and allow integrity protection of UDP communications,
NAT ALGs for UDP-based protocols SHOULD be turned off.
'''

[[spec]]
level = "SHOULD"
quote = '''
a) If a NAT includes ALGs, it is RECOMMENDED that the NAT allow
the NAT administrator to enable or disable each ALG separately.
'''

[[spec]]
level = "MUST"
quote = '''
REQ-11:  A NAT MUST have deterministic behavior, i.e., it MUST NOT
change the NAT translation (Section 4) or the Filtering
(Section 5) Behavior at any point in time, or under any particular
conditions.
'''

[[spec]]
level = "MUST"
quote = '''
REQ-12:  Receipt of any sort of ICMP message MUST NOT terminate the
NAT mapping.
'''

[[spec]]
level = "SHOULD"
quote = '''
a) The NAT's default configuration SHOULD NOT filter ICMP messages
based on their source IP address.
'''

[[spec]]
level = "SHOULD"
quote = '''
b) It is RECOMMENDED that a NAT support ICMP Destination
Unreachable messages.
'''

[[spec]]
level = "MUST"
quote = '''
REQ-13  If the packet received on an internal IP address has DF=1,
the NAT MUST send back an ICMP message "Fragmentation needed and
DF set" to the host, as described in [RFC0792].
'''

[[spec]]
level = "MUST"
quote = '''
a) If the packet has DF=0, the NAT MUST fragment the packet and
SHOULD send the fragments in order.
'''

[[spec]]
level = "MUST"
quote = '''
REQ-14:  A NAT MUST support receiving in-order and out-of-order
fragments, so it MUST have "Received Fragment Out of Order"
behavior.
'''

[[spec]]
level = "MUST"
quote = '''
a) A NAT's out-of-order fragment processing mechanism MUST be
designed so that fragmentation-based DoS attacks do not
compromise the NAT's ability to process in-order and
unfragmented IP packets.
'''

