target = "https://www.rfc-editor.org/rfc/rfc4787#section-4.1"


[[spec]]
level = "MUST"
quote = '''
REQ-1:  A NAT MUST have an "Endpoint-Independent Mapping" behavior.
'''

[[spec]]
level = "SHOULD"
quote = '''
REQ-2:  It is RECOMMENDED that a NAT have an "IP address pooling"
behavior of "Paired".
'''

