target = "https://www.rfc-editor.org/rfc/rfc4787#section-7"


[[spec]]
level = "SHOULD"
quote = '''
REQ-10:  To eliminate interference with UNSAF NAT traversal
mechanisms and allow integrity protection of UDP communications,
NAT ALGs for UDP-based protocols SHOULD be turned off.
'''

[[spec]]
level = "SHOULD"
quote = '''
a) If a NAT includes ALGs, it is RECOMMENDED that the NAT allow
the NAT administrator to enable or disable each ALG separately.
'''

