[profile.default]
retries = 3
test-threads = "num-cpus"
status-level = "all"
final-status-level = "all"
failure-output = "immediate"
success-output = "immediate"
fail-fast = "false"

[profile.default.junit]
path = "default.xml"
store-success-output = true
store-failure-output = true

[profile.dev]

[profile.dev.junit]
path = "dev.xml"
store-success-output = true
store-failure-output = true

[profile.release]
[profile.release.junit]
path = "release.xml"
store-success-output = true
store-failure-output = true
