[package]
name = "scratch"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
# internal
#dpdk = { workspace = true }
#dpdk-sys = { workspace = true }

# external
rand = { workspace = true }
tracing = { workspace = true, features = ["attributes", "max_level_debug"] }
tracing-subscriber = { workspace = true }
