[book]
authors = ["Daniel Noland"]
language = "en"
multilingual = false
src = "src"
title = "Hedgehog Dataplane Design Notes"

[preprocessor.plantuml]
plantuml-cmd = "/bin/plantuml"
after = ["links"]

[preprocessor.mermaid]
after = ["links"]

[preprocessor.katex]
macros = "src/macros.tex"
after = ["links"]
block-delimiter = { left = "``` equation", right = "```" }
inline-delimiter = { left = "`$", right = "$`" }
no-css = true
trust = true
strict = false

[preprocessor.alerts]

[output]

[output.html]
additional-css = []
smart-punctuation = true
preferrred-dark-theme = "ayu"
default-theme = "light"
