[book]
authors = ["Daniel Noland"]
language = "en"
multilingual = false
src = "src"
title = "Hedgehog Dataplane Design Notes"

[preprocessor.plantuml]
#plantuml-cmd = "/lib/openjdk/bin/java -jar /lib/plantuml.jar"
plantuml-cmd = "/bin/plantuml"
after = ["links"]
use-data-uris = false

[preprocessor.mermaid]
after = ["links"]

[preprocessor.katex]
macros = "src/macros.tex"
after = ["links"]
block-delimiter = { left = "``` equation", right = "```" }
inline-delimiter = { left = "`$", right = "$`" }
no-css = true
trust = true
strict = false

[preprocessor.alerts]

[output]

[output.html]
additional-css = []
additional-js = ["./theme/external/mermaid.min.js", "./theme/external/mermaid-init.js"]
smart-punctuation = true
preferrred-dark-theme = "ayu"
default-theme = "light"
