[package]
name = "errno"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]

thiserror = { workspace = true }

[build-dependencies]
dpdk-sysroot-helper = { path = "../dpdk-sysroot-helper" }
