name: Build and deploy docs
on:
  pull_request:
    paths:
      - '*.nix'
      - 'design-docs/**'
      - 'nix/**'
      - '.github/workflows/build-and-deploy-docs.yml'
  push:
    branches:
      - 'main'
    paths:
      - '*.nix'
      - 'design-docs/**'
      - 'nix/**'
      - '.github/workflows/build-and-deploy-docs.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Extract git hash
        shell: bash
        run: echo "git_hash=${GITHUB_SHA}" >> $GITHUB_OUTPUT
        id: extract_hash

      - name: Install nix
        uses: cachix/install-nix-action@v27

      - name: Nix cache
        id: cache-nix-packages
        uses: actions/cache@v4
        with:
          path: ~/work/nix-store
          key: cache-nix-${{ runner.os }}-${{ hashFiles('./flake.lock') }}

      - name: Build design docs
        run: |
          mkdir --parent ~/work/nix-store
          mkdir --parent ~/work/out
          nix build '#design-docs' --store ~/work/nix-store --out-link ~/work/out/design-docs

      - name: Copy design doc build to publish directory
        run: |
          set -euxo pipefail
          mkdir --parent ${{ github.workspace }}/publish/
          cp -r ~/work/nix-store/nix/store/"$(basename "$(readlink ~/work/out/design-docs)")" ${{ github.workspace }}/publish/design-docs

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload design-docs
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload design-docs build directory content
          path: 'publish/design-docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
