# Make sure justfile source code is consistently formatted.

name: "lint-just-fmt.yml"

on:
  pull_request:
    paths:
      - "justfile"
      - ".github/workflows/lint-just-fmt.yml"
  merge_group:
    types: ["checks_requested"]

concurrency:
  group: "${{ github.workflow }}:${{ github.event.pull_request.number || github.event.after || github.event.merge_group && github.run_id }}"
  cancel-in-progress: true

jobs:
  format-check:
    name: "Check formatting"
    runs-on: "ubuntu-latest"
    # Skip this job in merge group checks; but we need the workflow to run,
    # given that the status check is required for merging.
    if: "${{ github.event.pull_request }}"
    steps:
      - name: "Install Rust toolchain"
        uses: "dtolnay/rust-toolchain@master"
        with:
          toolchain: "nightly"
          components: "rustfmt"

      - name: "Install just"
        run: |
          cargo install just

      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: "1"
          persist-credentials: "false"

      - name: "Check formatting of just code"
        run: |
          just --fmt --check --unstable

      - name: "How to fix"
        if: ${{ failure() }}
        run: |
          just --dump 

