# Make sure we don't have obvious vulns / anti patterns in our code or
# actions config.

name: "lint-opengrep.yml"

on:
    pull_request: {}
    merge_group:
        types: ["checks_requested"]

concurrency:
    group: "${{ github.workflow }}:${{ github.event.pull_request.number || github.event.after || github.event.merge_group && github.run_id }}"
    cancel-in-progress: true

permissions:
    contents: "read"

jobs:
    format-check:
        name: "Run opengrep"
        runs-on: "lab"
        # Skip this job in merge group checks; but we need the workflow to run,
        # given that the status check is required for merging.
        if: "${{ github.event.pull_request }}"
        env:
            USER: "runner"
        steps:
            - name: "Checkout"
              uses: "actions/checkout@v6"
              with:
                  fetch-depth: "1"
                  persist-credentials: "false"

            - name: "Install nix"
              uses: "cachix/install-nix-action@v31"
              with:
                  github_access_token: "${{ secrets.GITHUB_TOKEN }}"
                  nix_path: "nixpkgs=channel:nixpkgs-unstable"

            - uses: "cachix/cachix-action@v17"
              with:
                  name: "hedgehog"
                  # prettier-ignore
                  signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
                  # prettier-ignore
                  authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

            - name: "Run opengrep"
              run: |
                  nix-shell --run 'opengrep scan --experimental'
