# The primary point of this workflow is to ensure that the developer experience is good.
# We take a very vanilla ubuntu image, install all necessary dependencies via "normal" means,
# and then run the build and test steps as described in the README.md file.

# The artifacts produced by these builds are not intended to be used for anything other than
# ensuring that the developer experience is good.

# Production artifacts are produced in a sterile environment (in another CI workflow).


name: Update Version
on:
  workflow_dispatch:
  push:
    branches:
      - real-readme



concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  just: 1.36.0

permissions:
  contents: write
  pull-requests: write
  packages: read
  id-token: write
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - run: ./scripts/update-versions.sh
      - run: uuidgen > biscuit
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: 'update-versions'
          title: 'Update versions'
          assignees: "daniel-noland"
          labels: "update,bot"
          maintainer-can-modify: 'true'
          sign-commits: 'true'
