name: "vlab-test.yml"

on:
  pull_request_review_comment: {}
  workflow_dispatch:
    inputs:
      dpdk-sys-commit:
        type: "string"
        description: "git sha of dpdk sys commit to use (picks frr)"
        required: true

jobs:
  vlab:
    name: "${{ matrix.image.dataplane }}"
    uses: githedgehog/fabricator/.github/workflows/run-vlab.yaml@master
    strategy:
      fail-fast: false
      matrix:
        fabricmode:
          - spine-leaf
        gateway:
          - true
        includeonie:
          - false
        buildmode:
          - "iso"
        vpcmode:
          - "l2vni"
          - "l3vni"
        hybrid:
          - false
        include:
          - fabricmode: "spine-leaf"
            gateway: true
            includeonie: false
            buildmode: "iso"
            vpcmode: "l2vni"
            hybrid: true
        image:
          - dataplane: "pr-daniel-noland-bump.x86_64-unknown-linux-gnu.debug.8a53c0e04327ed5f64ea927ebf5d3cfd6c901851"
            frr: "${{ inputs.dpdk_sys_commit }}.debug"
          - dataplane: "pr-daniel-noland-bump.x86_64-unknown-linux-gnu.release.8a53c0e04327ed5f64ea927ebf5d3cfd6c901851"
            frr: "${{ inputs.dpdk_sys_commit }}.release"

    with:
      fabricatorref: master
      prebuild: |
        just bump dataplane ${{matrix.image.dataplane}}
        just bump frr ${{matrix.image.frr}}
      fabricmode: ${{ matrix.fabricmode }}
      gateway: ${{ matrix.gateway }}
      includeonie: ${{ matrix.includeonie }}
      buildmode: ${{ matrix.buildmode }}
      vpcmode: ${{ matrix.vpcmode }}
      releasetest: false
      hybrid: ${{ matrix.hybrid }}
