name: "vlab-test.yml"

on:
  pull_request_review_comment: {}
  check_run:
    types:
      - completed

  workflow_dispatch:
    inputs:
      dpdk-sys-commit:
        type: "string"
        description: "git sha of dpdk sys commit to use (picks frr)"
        required: true
        default: "475176418d4294031aacbe9082f17c5b6675529c.debug"

jobs:
  vlab:
    name: "${{ matrix.image.dataplane }}"
    uses: githedgehog/fabricator/.github/workflows/run-vlab.yaml@master
    strategy:
      fail-fast: false
      matrix:
        fabricmode:
          - spine-leaf
        gateway:
          - true
        includeonie:
          - false
        buildmode:
          - "iso"
        vpcmode:
          - "l2vni"
          - "l3vni"
        hybrid:
          - false
        image:
          - dataplane: "${{ inputs.dataplane_image || 'main.debug' }}"
            frr: "${{ inputs.frr_image || '475176418d4294031aacbe9082f17c5b6675529c.debug' }}"

    with:
      fabricatorref: master
      prebuild: |
        just bump dataplane ${{ matrix.image.dataplane }}
        just bump frr ${{ matrix.image.frr }}
      fabricmode: ${{ matrix.fabricmode }}
      gateway: ${{ matrix.gateway }}
      includeonie: ${{ matrix.includeonie }}
      buildmode: ${{ matrix.buildmode }}
      vpcmode: ${{ matrix.vpcmode }}
      releasetest: false
      hybrid: ${{ matrix.hybrid }}
