name: "vlab.yml"

on:
  pull_request: {}
  push:
    branches:
      - pr/daniel-noland/bump
  workflow_dispatch:
    inputs:
      fabricatorref:
        type: "string"
        description: "the fabricator git ref to use as the basis of this test"
        required: true
        default: "pr/daniel-noland/tmate-hack"
      dataplane_image:
        type: "string"
        description: "tag of the dataplane image to use"
        required: true
        default: "main.debug"
      frr_image:
        type: "string"
        description: "tag of the dpdk-sys built frr image to use"
        required: true
        default: "7c45af7c234826eec19a69f1b662ad3185a62d5e.debug"

jobs:
  vlab:
    name: "${{ matrix.image.frr }}-${{ matrix.image.dataplane }}"
    uses: githedgehog/fabricator/.github/workflows/run-vlab.yaml@pr/daniel-noland/tmate-hack
    strategy:
      fail-fast: false
      matrix:
        fabricatorref:
          - ${{ inputs.fabricatorref || 'pr/daniel-noland/tmate-hack' }}
        fabricmode:
          - "spine-leaf"
        gateway:
          - true
        includeonie:
          - false
        buildmode:
          - "iso"
        vpcmode:
          - "l2vni"
          - "l3vni"
        hybrid:
          - false
        image:
          - dataplane: "${{ inputs.dataplane_image || 'main.debug' }}"
            frr: "${{ inputs.frr_image || '7c45af7c234826eec19a69f1b662ad3185a62d5e.debug' }}"

    with:
      fabricatorref: ${{ matrix.fabricatorref }}
      prebuild: |
        just bump dataplane ${{ matrix.image.dataplane }}
        just bump frr ${{ matrix.image.frr }}
      fabricmode: ${{ matrix.fabricmode }}
      gateway: ${{ matrix.gateway }}
      includeonie: ${{ matrix.includeonie }}
      buildmode: ${{ matrix.buildmode }}
      vpcmode: ${{ matrix.vpcmode }}
      releasetest: false
      hybrid: ${{ matrix.hybrid }}
      debug: true
